[project]
name = "llmpipe"
version = "0.1.0"
description = "A toolkit for building LLM pipelines"
authors = [
    {name = "John Dunavent", email = "dunavent.jm@gmail.com"},
]
dependencies = [
    "typer",
    "polars",
    "torch",
    "transformers",
    "datasets",
    "boto3",
    "scikit-learn",
    "scipy",
    "nltk",
    "matplotlib",
    "seaborn",
    "accelerate"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "aider-chat",
    "pytest",
    "ipython",
    "nb-clean",
    "pytest-cov",
    "pdoc3"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
